---
title: "Diet Exp1 Development"
output: html_notebook
---
```{r setup}
library("tidyverse")
library("tidyr")
library("ggplot2")
library("ggpubr")
library("dplyr")
library("nlme")
library("gridExtra")
```


```{r regressing development metrics against predictor variables}

summary(lm(hatchToIns5_DR~Diet+Sex+Infection,data=ddata))
summary(lm(numDaysHatchToIns5~Diet+Sex+Infection, data=ddata))
summary(lm(pupation~Diet+Sex+Infection,data=ddata))
summary(lm(numDaysHatchToEclose~Diet+Sex+Infection, data=ddata))
summary(lm(critical_period~Diet+Sex+Infection, data=ddata))  #This is where diet is the most significant
summary(lm(numDaysHatchtoPup~Diet+Sex+Infection, data=ddata))

```


```{r development plots} 

# How to generate individual development rates
ggplot(data=ddata.tidy %>% filter(LarvID==17),aes(x=date,y=stage))+geom_point()+geom_smooth(aes(y=as.numeric(stage)),method="lm",se=FALSE) 

#Average development rates
overallDRplot <- ggplot(data=ddata.tidy,aes(x=date,y=stage,group=Diet,color=factor(Diet),fill=factor(Diet)))+
 geom_smooth(aes(y=stage),se=TRUE) 

total_development <- ggplot(ddata.tidy %>% filter(stage == "HatchDate" | stage=="EcloseDate"), aes(x=date,y=stage, group=Diet,color=factor(Diet), fill=factor(Diet))) +
  geom_smooth(aes(y=stage), method="lm", se=TRUE) +
  labs(x="Date", y="Stage", title="Development Time from Hatching through Eclosure")

#Boxplot for host plant species v. overall development rate/days to development
DRcomparisonplot <- ggboxplot(ddata, x="Diet", y="numDaysHatchToEclose", fill="lightblue") +
labs(y="Overall Development Rate", x = "Host Plant Species") + 
ggtitle("Number of days") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(DRcomparisonplot)

# stacked bar chart
totaldvlpbar<-ggplot(data=totaldata1_pivot%>% group_by(diet, stage_transition) %>% summarize(mean_duration=mean(duration,na.rm=T)),
       aes(x=diet,y=mean_duration,fill=stage_transition)) + 
  geom_bar(position=position_stack(reverse=T),stat="identity") +
  labs(x="Diet", y="Number of days", title = "Time spent in each larval development stage") +
  scale_fill_discrete(name="Stage", breaks=c("hatch_ins2....hatch_ins2", "ins2_ins3", "ins3_ins4", "ins4_ins5", "critical_period", "pupation"), labels=c("First instar", "Second instar", "Third instar", "Fourth instar", "Fifth instar", "Pupation"))

#stacked bar chart accounting for sex instead of diet
totaldvlpsexbar<-ggplot(data=totaldata1_pivot%>% group_by(sex, stage_transition) %>% summarize(mean_duration=mean(duration,na.rm=T)),
       aes(x=sex,y=mean_duration,fill=stage_transition)) + 
  geom_bar(position=position_stack(reverse=T),stat="identity") +
  labs(x="Diet", y="Number of days", title = "Time spent in each larval development stage") +
  scale_fill_discrete(name="Stage", breaks=c("hatch_ins2....hatch_ins2", "ins2_ins3", "ins3_ins4", "ins4_ins5", "critical_period", "pupation"), labels=c("First instar", "Second instar", "Third instar", "Fourth instar", "Fifth instar", "Pupation"))

#Transition rates for each larval stage
hatch_ins2plot <- ggplot(ddata.tidy %>% filter(stage == "HatchDate" | stage=="Ins2"), aes(x=date,y=stage,group=Diet,color=factor(Diet), fill=factor(Diet))) +
  geom_smooth(aes(y=stage), method="lm", se=TRUE)
print(hatch_ins2plot)

ins2_ins3plot <- ggplot(ddata.tidy %>% filter(stage == "Ins2" | stage=="Ins3"), aes(x=date,y=stage,group=Diet,color=factor(Diet), fill=factor(Diet))) +
  geom_smooth(aes(y=stage), method="lm", se=TRUE)
print(ins2_ins3plot)

ins3_ins4plot <- ggplot(ddata.tidy %>% filter(stage == "Ins3" | stage=="Ins4"), aes(x=date,y=stage,group=Diet,color=factor(Diet), fill=factor(Diet))) +
  geom_smooth(aes(y=stage), method="lm", se=TRUE)
print(ins3_ins4plot)

ins4_ins5plot <- ggplot(ddata.tidy %>% filter(stage == "Ins4" | stage=="Ins5"), aes(x=date,y=stage,group=Diet,color=factor(Diet), fill=factor(Diet))) +
  geom_smooth(aes(y=stage), method="lm", se=TRUE)
print(ins4_ins5plot)

pupationplot <- ggplot(data=ddata.tidy %>% filter(stage == "Ins5" | stage== "PupDate"),aes(x=date,y=stage,group=Diet,color=factor(Diet),fill=factor(Diet)))+
  geom_smooth(aes(y=stage),method="lm",se=TRUE)

```

```{r development MANCOVA + group means}

group_by(totaldata1, sex, diet) %>%
  summarise(count=n(), mean=mean(numDaysHatchToEclose, na.rm=TRUE), sd=sd(numDaysHatchToEclose, na.rm=TRUE))

group_by(totaldata1, sex, diet) %>%
  summarise(count=n(), mean=mean(critical_period, na.rm=TRUE), sd=sd(critical_period, na.rm=TRUE))

#Male overall development rate ~ diet * infection
y_ODRm <- cbind(maledata$hatch_ins2....hatch_ins2, maledata$ins2_ins3, maledata$ins3_ins4, maledata$ins4_ins5, maledata$critical_period, maledata$pupation)
fity_ODRm <- manova(y_ODRm ~ diet*infection, data=maledata)
summary.aov(fity_ODRm)

#Female overall development rate ~ diet * infection
y_ODRf <- cbind(femaledata$hatch_ins2....hatch_ins2, femaledata$ins2_ins3, femaledata$ins3_ins4, femaledata$ins4_ins5, femaledata$critical_period, femaledata$pupation)
fity_ODRf <- manova(y_ODRf ~ diet*infection, data=femaledata)
summary.aov(fity_ODRf)
```

```{r MANCOVA development ~ morph/pigmentation}
#MANCOVA for pigmentation~ numDaysHatchto Eclose
yODRcm <- cbind(maledata$Redhue, maledata$Redsat, maledata$Redint, maledata$percent.mel, maledata$Blkdens)
fityODRcm <- manova(yODRcm ~ numDaysHatchToEclose, data=maledata)
summary.aov(fityODRcm)

yODRcf <- cbind(femaledata$Redhue, femaledata$Redsat, femaledata$Redint, femaledata$percent.mel, femaledata$Blkdens)
fityODRcf <- manova(yODRcf ~ numDaysHatchToEclose + critical_period, data=femaledata)
summary.aov(fityODRcf)

#ANOVAs and plots for forewing morphology
options(contrasts=c("contr.helmert", "contr.poly"))
d1 <- lm(fore.area~numDaysHatchToEclose, data=totaldata1)
d1aov <- aov(d1, type="marginal", data=totaldata1)
anova(d1aov)
coef(d1)

d1l <-lm(fore.length~numDaysHatchToEclose, data=totaldata1)
d1laov <- aov(d1l, type="marginal", data=totaldata1)
anova(d1laov)
coef(d1l)

d1w <-lm(fore.width~numDaysHatchToEclose, data=totaldata1)
d1waov <- aov(d1w, type="marginal", data=totaldata1)
anova(d1waov)
coef(d1w)


#Forewing Plots w/o diet
d1plot <- ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=fore.area)) +
  geom_smooth(method="lm") +
  geom_point(aes(color=factor(diet))) +
  geom_errorbar(aes(ymin=)) +
  stat_cor() +
  labs(x=NULL, y="Forewing Area (cm sq.)")

d1lplot <- ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=fore.length)) +
  geom_smooth(method="lm") +
  stat_cor() +
  labs(x=NULL, y="Forewing Length (cm)")

d1wplot <- ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=fore.width)) +
  geom_smooth(method="lm") +
  stat_cor() +
  labs(x=NULL, y="Forewing Width (cm)")

ggarrange(d1plot, d1lplot, d1wplot, labels=c("A", "B", "C"), ncol=2, nrow=2)


#ANOVAs for hindwings 


#Hindwing Plots
d2 <- lm(hind.area~numDaysHatchToEclose, data=totaldata1)
d2aov <- aov(d2, type="marginal", data=totaldata1)
anova(d2aov)
coef(d2)

d2l <-lm(hind.length~numDaysHatchToEclose, data=totaldata1)
d2laov <- aov(d2l, type="marginal", data=totaldata1)
anova(d2laov)
coef(d2l)

d2w <- lm(hind.width~numDaysHatchToEclose, data=totaldata1)
d2waov <- aov(d2w, type="marginal", data=totaldata1)
anova(d2waov)
coef(d2w)

d2plot <- ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=hind.area, color=factor(diet))) +
  geom_smooth(method="lm") +
  geom_point() +
  stat_cor() +
  labs(x="Development Time (# of Days)", y="Hindwing Area")
print(d2plot)

d3 <- lm(percent.mel~numDaysHatchToEclose, data=totaldata1)
d3aov <- aov(d3, type="marginal", data=totaldata1)
anova(d3aov)
coef(d3)

d3plot <- ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=percent.mel)) +
  geom_smooth(method="lm") +
  geom_point() +
  stat_cor() +
  labs(x="Development Time (# of Days)", y="Percentage of Melanin")
print(d3plot)

d4plot <-ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=Redhue, color=factor(diet))) +
  geom_smooth(method="lm") +
  geom_point() +
  stat_cor() +
  labs(x="Development Time (# of Days)", y="Red Hue")
print(d4plot)

d4satplot <- ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=Redsat)) +
  geom_smooth(method="lm") +
  geom_point() +
  stat_cor() +
  labs(x="Development Time (# of Days)", y="Red Saturation")

d5plot <-ggplot(totaldata1, aes(x=numDaysHatchToEclose, y=hind.area.asym)) +
  geom_smooth(method="lm") +
  geom_point() +
  stat_cor() +
  labs(x="Development Time (# of Days)", y="Asym")
print(d5plot)

#Forewing morph ~ dvlpmt MANCOVA
yfwm_m <- cbind(maledata$fore.area, maledata$fore.length, maledata$fore.width, maledata$fore.round, maledata$fore.asp.ratio)
fit_yfwm_m <- manova(yfwm_m ~ critical_period + numDaysHatchToEclose, data=maledata)
summary.aov(fit_yfwm_m)

yfwm_f <- cbind(femaledata$fore.area, femaledata$fore.length, femaledata$fore.width, femaledata$fore.round, femaledata$fore.asp.ratio)
fit_yfwm_f <- manova(yfwm_f ~ numDaysHatchToEclose + critical_period, data=femaledata)
summary.aov(fit_yfwm_f)

#Hindwing morph ~ dvlpmt MANCOVA
yhwm_m <- cbind(maledata$hind.length, maledata$hind.width, maledata$hind.area)
fit_yhwm_m <- manova(yhwm_m ~ numDaysHatchToEclose + critical_period, data=maledata)
summary.aov(fit_yhwm_m)

yhwm_f <- cbind(femaledata$hind.length, femaledata$hind.width, femaledata$hind.area)
fit_yhwm_f <- manova(yhwm_f ~ numDaysHatchToEclose + critical_period, data=femaledata)
summary.aov(fit_yhwm_f)

#NOT divided by sex FW
yfw <- cbind(totaldata1$fore.area, totaldata1$fore.length, totaldata1$fore.width, totaldata1$fore.asp.ratio, totaldata1$fore.round)
fit_yfw <- manova(yfw ~ numDaysHatchToEclose + critical_period, data=totaldata1)
summary.aov(fit_yfw)

#NOT divided by sex HW
yhw <- cbind(totaldata1$hind.area, totaldata1$hind.length, totaldata1$hind.width)
fit_yhw <- manova(yhw ~ numDaysHatchToEclose + critical_period, data=totaldata1)
summary.aov(fit_yhw)

#Asym
y_asym <- cbind(totaldata1$fore.area.asym, totaldata1$fore.length.asym, totaldata1$hind.area.asym, totaldata1$hind.length.asym)
fity_asym <- manova(y_asym ~ numDaysHatchToEclose + critical_period, data=totaldata1)
summary.aov(fity_asym)

#Pigmentation
y_pig <- cbind(totaldata1$Redhue, totaldata1$Redsat, totaldata1$Redint, totaldata1$percent.mel, totaldata1$Blkdens)
fity_pig <- manova(y_pig ~ numDaysHatchToEclose + critical_period, data=totaldata1)
summary.aov(fity_pig)

```

