---
title: "Diet Experiment 1 Morph Summarize"
author: "Caitlin Ducat"
date: "3/13/2020"
output: html_document
---
```{r setup, include=FALSE}


library("tidyverse")
library("tidyr")
library("dplyr")
library("nlme")
library("pwr")
library("ggplot2")
library("ggpubr")
library("pear")
library("compute.es")
```


```{r cleaning MORPH data}
dietmorph <- read.csv("morphclean.csv")

#averaging area for hindwings and forewings; calculating area asymmetry
dietmorph<-left_join(dietmorph, dietmorph %>% select(specimen,wing,area) %>% spread(key=wing,area) %>% 
  transmute(specimen=specimen,fore.area=(LFW+RFW)/2,hind.area=(LHW+RHW)/2, 
            fore.area.asym=LFW-RFW,hind.area.asym=LHW-RHW))

#averaging length for hindwings and forewings; calculating length asymmetry
dietmorph<-left_join(dietmorph, dietmorph %>% select(specimen,wing,length) %>% spread(key=wing,length) %>% 
  transmute(specimen=specimen,fore.length=(LFW+RFW)/2,hind.length=(LHW+RHW)/2, 
            fore.length.asym=LFW-RFW,hind.length.asym=LHW-RHW))

#averaging width for hindwings and forewings
dietmorph <- left_join(dietmorph, dietmorph %>% select(specimen,wing,breadth) %>% spread(key=wing,breadth) %>% transmute(specimen=specimen, fore.width=(LFW+RFW)/2, hind.width=(LHW+RHW)/2))

#averaging forewing roundness
dietmorph<-left_join(dietmorph, dietmorph %>% select(specimen,wing,roundness) %>% spread(key=wing,roundness) %>%
  transmute(specimen=specimen,fore.round=(LFW+RFW)/2))

#calculating aspect ratio
dietmorph <- left_join(dietmorph, dietmorph %>% select(specimen,wing,asp.ratio) %>% spread(key=wing,asp.ratio) %>% transmute(specimen=specimen, fore.asp.ratio=(LFW+RFW)/2))



dietmorph1 <- subset(dietmorph, wing=="LFW") #gets rid of duplicates
dietmorph2 <- select(dietmorph1, -c(wing, area, length, breadth, roundness, asp.ratio)) #final product for analyses
```
```{r COLOR data}
#cleaned/averaged by hand
dietcolor <- read_csv("DietExp1_ColorClean.csv")
dietcolor1 <- dietcolor[-48,] #this case is missing data
```

```{r DEVELOPMENT data}
# Read Development Data
ddata <- read.csv("Diet1DvlpDataClean.csv")
ddata$Ins2<-as.Date(as.character(ddata$Ins2),format="%d-%b")  # fix the year problem
ddata$Ins3<-as.Date(as.character(ddata$Ins3),format="%d-%b")
ddata$Ins4<-as.Date(as.character(ddata$Ins4),format="%d-%b")
ddata$Ins5<-as.Date(as.character(ddata$Ins5),format="%d-%b")
ddata$HatchDate<-as.Date(as.character(ddata$HatchDate),format="%d-%b")
ddata$PupDate<-as.Date(as.character(ddata$PupDate),format="%d-%b")
ddata$EcloseDate<-as.Date(as.character(ddata$EcloseDate),format="%d-%b")
summary(ddata)

# Create response variables
ddata.tidy<-gather(ddata, key="stage",value="date",-LarvID,-Diet,-FamLine,-Infection,-Dead,-Sex, -X)
ddata.tidy$stage<-factor(ddata.tidy$stage,levels=c("HatchDate","Ins2", "Ins3","Ins4","Ins5","PupDate","EcloseDate"))
ddata.tidy$stageNum<-as.numeric(ddata.tidy$stage)-1

  
larvae_ids<-unique(ddata.tidy$LarvID)
# for each larva, calculate development rate metrics
overall_DR<-c() #rate
numDaysHatchToEclose<-c() #days
hatchToIns5_DR<-c() #rate
numDaysHatchToIns5<-c() #days
pupation<-c() #days
critical_period<-c() #days
numDaysHatchtoPup <- c() #days
hatch_ins2 <- c()
ins2_ins3 <- c()
ins3_ins4 <- c()
ins4_ins5 <- c()


for(i in 1:length(larvae_ids))
{
  larvaData<-ddata.tidy %>% filter(LarvID==larvae_ids[i])
  # stages per day, all stages from Hatch to Eclose (or last stage reached)
  #overall_DR[i]<- 1/coef(lm(stageNum~date,data=larvaData))[2] 
  
  # days from hatch to eclosure
  numDaysHatchToEclose[i]<-larvaData$date[larvaData$stage=="EcloseDate"]-larvaData$date[larvaData$stage=="HatchDate"]
  
  # stages from Hatch to 5th instar (or last stage reached)
  # hatchToIns5_DR[i]<-1/coef(lm(stageNum~date,data=larvaData %>% filter(stageNum<5)))[2] 
  
  # days from hatching to 5th instar
  numDaysHatchToIns5[i]<-larvaData$date[larvaData$stage=="Ins5"]-larvaData$date[larvaData$stage=="HatchDate"]
  
  #duration of pupation
  pupation[i]<-larvaData$date[larvaData$stage=="EcloseDate"]-larvaData$date[larvaData$stage=="PupDate"]
  
  #Period from 5th instar to pupa
  critical_period[i]<-larvaData$date[larvaData$stage=="PupDate"]-larvaData$date[larvaData$stage=="Ins5"]
  
  #Hatch through pupation
  numDaysHatchtoPup[i] <- larvaData$date[larvaData$stage=="PupDate"]-larvaData$date[larvaData$stage=="HatchDate"]
  
  #Instar moults
  hatch_ins2[i] <- larvaData$date[larvaData$stage=="Ins2"]-larvaData$date[larvaData$stage=="HatchDate"]
  ins2_ins3[i] <- ins2_ins3[i] <- larvaData$date[larvaData$stage=="Ins3"]-larvaData$date[larvaData$stage=="Ins2"]
  ins3_ins4[i] <- ins3_ins4[i] <- larvaData$date[larvaData$stage=="Ins4"]-larvaData$date[larvaData$stage=="Ins3"]
  ins4_ins5[i] <- ins4_ins5[i] <- larvaData$date[larvaData$stage=="Ins5"]-larvaData$date[larvaData$stage=="Ins4"]
  
}

df<-data.frame(LarvID=larvae_ids,numDaysHatchToEclose=numDaysHatchToEclose,numDaysHatchToIns5=numDaysHatchToIns5,hatch_ins2 <-hatch_ins2, ins2_ins3=ins2_ins3, ins3_ins4=ins3_ins4, ins4_ins5=ins4_ins5, critical_period=critical_period, pupation=pupation, numDaysHatchtoPup=numDaysHatchtoPup)

#put back into original data, remove comments column
ddata<-left_join(ddata,df,by="LarvID")
```

```{r Merging data frames/creating pivot table}
#change column name from 'LarvID' to 'specimen' in 'df' dataframe in order to merge dataframes by specimen
names(ddata)[names(ddata)=="LarvID"] <- "specimen"
names(dietcolor1)[names(dietcolor1)=="Specimen"] <- "specimen"
#Merge dataframes -- morph and color with development rate
totaldata <- merge(dietmorph2,dietcolor1, by="specimen")
totaldata1 <- merge(totaldata,ddata, by="specimen")

#Removing duplicate or unnecessary columns
totaldata1$Diet.x <- NULL
totaldata1$Diet.y <- NULL
totaldata1$Sex.x <- NULL
totaldata1$Sex.y <- NULL
totaldata1$FamLine <- NULL
totaldata1$Famline <- NULL
totaldata1$Infection.x <- NULL
totaldata1$Infection.y <- NULL
totaldata1$X <- NULL
totaldata1$Dead <- NULL

totaldata1_pivot<-totaldata1 %>% pivot_longer(c("hatch_ins2....hatch_ins2","ins2_ins3" ,"ins3_ins4" ,"ins4_ins5","critical_period", "pupation"),names_to="stage_transition",values_to="duration")
totaldata1_pivot$stage_transition<-factor(totaldata1_pivot$stage_transition,levels=c("hatch_ins2....hatch_ins2","ins2_ins3","ins3_ins4","ins4_ins5","critical_period", "pupation"))

```

```{r frequency tables}
attach(dietmorph2)
diet.table <- table(sex, diet, infection)
print(diet.table)

table <- table(diet)
print(table)

inf.table <- table(sex, infection)
print(inf.table)
```

```{r forewing area}
#Used gls instead of lme because predictor variables are categorical, not continuous. Thus it's not a linear model, but a generalized least squares regression. aov() is better than anova() in this scenario because it internally calls lm(), which fits the model

summary(dietmorph2)
#original model
m1 <- gls(fore.area ~ diet*sex*infection, data=dietmorph2)
m1aov <- aov(m1)
anova(m1aov)


#residuals plot
m1resid <-resid(m1, type="response")
plot(m1resid)

#model with infeciton as random effect
m1random <- lme(fore.area ~ diet+sex, random= ~1 | infection, data=dietmorph2)
summary(m1random)

#varIdent models
mf1 <- varIdent(form=~1|diet)
m1.vident <- gls(fore.area ~ diet+sex+infection, weights=mf1, data=dietmorph2)

mf2 <- varIdent(form=~1|infection)
m1.vident2 <- gls(fore.area ~ diet+sex+infection, weights=mf2)

mf3 <- varIdent(form=~1|sex)
m1.vident3 <- gls(fore.area ~ diet+sex+infection, weights=mf3)

#AIC comparision of original and random models
anova(m1, m1.vident, m1.vident2, m1.vident3) #retain original model

#standardized results
par(mfrow = c(1,2))
plot(dietmorph2$diet, resid(m1, type="response"), cex.axis=.5,
cex=.4, xlab="Diet", ylab="ordinary resid", cex.lab=.8)
plot(dietmorph2$diet, resid(m1, type="normalized"), cex.axis=.5,
cex=.4, xlab="Diet", ylab="standardized resid", cex.lab=.8)

#standardized results v fitted values
par(mfrow = c(1,2))
plot(fitted(m1), resid(m1, type="normalized"), cex.axis=.5,
cex=.4, xlab="fitted values", ylab="standardized resid", cex.lab=.8)
plot(dietmorph2$diet, resid(m1, type="normalized"), cex.axis=.5,
cex=.4, xlab="diet", ylab="standardized resid", cex.lab=.8)

```

```{r hindwing area}
m2 <- gls(hind.area ~ diet*sex*infection, data=dietmorph2)
m2aov <- aov(m2, type="marginal")
anova(m2aov)

m2resid <- resid(m2, type="response")
plot(m2resid)

m2random <- lme(hind.area ~ diet+sex, random= ~1 | infection, data=dietmorph2)
summary(m2random)

m2f1 <- varIdent(form=~1|diet)
m2.vident <- gls(hind.area ~ diet+sex+infection, weights=mf1, data=dietmorph2)

m2f2 <- varIdent(form=~1|infection)
m2.vident2 <- gls(hind.area ~ diet+sex+infection, weights=mf2)

m2f3 <- varIdent(form=~1|sex)
m2.vident3 <- gls(hind.area ~ diet+sex+infection, weights=mf3)

anova(m2, m2random, m2.vident, m2.vident2, m2.vident3) #retain original model
```

```{r forewing area symmetry}

m3 <- gls(fore.area.asym ~ diet * sex * infection, data=dietmorph2)
m3aov <- aov(m3, type="marginal")
anova(m3aov)
```

```{r hindwing area asymmetry}
m4 <- gls(hind.area.asym ~ diet * sex * infection, data=dietmorph2)
m4aov <- aov(m4, type="marginal")
anova(m4aov)
```

```{r forewing roundness}

m5 <- gls(fore.round ~ diet * sex * infection, data=dietmorph2)
m5aov <- aov(m5, type="marginal")
anova(m5aov)
```

```{r forewing length and width}

m6 <- gls(fore.length ~ diet * sex * infection, data=dietmorph2)
m6aov <- aov(m6, type="marginal")
anova(m6aov)

m7 <- gls(fore.width ~ diet * sex * infection, data=dietmorph2)
m7aov <- aov(m7, type="marginal")
anova(m7aov)
```

```{r forewing aspect ratio}

m8 <- gls(fore.asp.ratio ~ diet * sex * infection, data=dietmorph2)
m8aov <- aov(m8, type="marginal")
anova(m8aov)
```

```{r hindwing length and width}

m9 <-gls(hind.length ~ diet * sex * infection, data=dietmorph2)
m9aov <- aov(m9, type="marginal")
anova(m9aov)

m10 <- gls(hind.width ~ diet * sex * infection, data=dietmorph2)
m10aov <- aov(m10, type="marginal")
anova(m10aov)
```


```{r color exploratory analyses}

c1<-gls(Redhue ~ Diet * Sex * Infection, data=dietcolor1) 
c1aov <- aov(c1,type="marginal", data=dietcolor1)
anova(c1aov)

c2<-gls(Redsat ~ Diet * Sex * Infection, data=dietcolor1) 
c2aov <- aov(c2, type="marginal", data=dietcolor1)
anova(c2aov)

c3<-gls(Redint ~ Diet * Sex * Infection, data=dietcolor1)
c3aov <- aov(c3, type="marginal", data=dietcolor1)
anova(c3aov)

c4 <- gls(Melarea ~ Diet * Sex * Infection, data=dietcolor1)
c4aov <- aov(c4, type="marginal", data=dietcolor1)
anova(c4aov)

c5 <- gls(Blkdens ~ Diet * Sex * Infection, data=dietcolor1)
c5aov <- aov(c5, type="marginal", data=dietcolor1)
anova(c5aov)

```

```{r morphology ANOVA plots}
compare_means(fore.area ~ diet, data=dietmorph2)
my_comparisons <- list(c("N", "T"))

#Forewing morphology and symmetry
dflength.plot <- ggboxplot(dietmorph2, x="diet", y="fore.length", fill="sex") +
labs(y="Forewing Length", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on forewing length") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dflength.plot)

dfwidth.plot <- ggboxplot(dietmorph2, x="diet", y="fore.width", fill="sex") +
labs(y="Forewing Width", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on forewing width") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dfwidth.plot)

dfarea.plot <- ggboxplot(dietmorph2, x="diet", y="fore.area", fill="sex") +
labs(y="Forewing Area", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on forewing area") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dfarea.plot)

dfasym.plot <- ggboxplot(dietmorph2, x="diet", y="fore.area.asym", fill="sex") +
labs(y="Forewing Asymmetry", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on forewing asymmetry") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dfasym.plot)

dfround.plot <- ggboxplot(dietmorph2, x="diet", y="fore.round", fill="sex") +
labs(y="Roundness", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on forewing roundness") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dfround.plot)


#Hindwing morphology and symmetry
dhlength.plot <- ggboxplot(dietmorph2, x="diet", y="hind.length", fill="sex") +
labs(y="Hindwing Length", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on hindwing length") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dhlength.plot)

dharea.plot <- ggboxplot(dietmorph2, x="diet", y="hind.area", fill="sex") +
labs(y="Hindwing Area", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on hindwing area") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dharea.plot)

dhasym.plot <- ggboxplot(dietmorph2, x="diet", y="hind.area.asym", fill="sex") +
labs(y="Hindwing Asymmetry", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on hindwing asymmetry") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(dhasym.plot)
  
```

```{r color ANOVA plots}

redhue.plot <- ggboxplot(dietcolor1, x="Diet", y="Redhue", fill="Sex") +
labs(y="Hue value", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on wing hue") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova")
print(redhue.plot)

redsat.plot <- ggboxplot(dietcolor1, x="Diet", y="Redsat", fill="Sex") +
labs(y="Saturation value", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on saturation of red pigment") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova", label="p.format")
print(redsat.plot)

redint.plot <- ggboxplot(dietcolor1, x="Diet", y="Redint", fill="Sex") +
labs(y="Intensity value", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on red intensity") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova", label="p.format")
print(redint.plot)

melarea.plot <- ggboxplot(dietcolor1, x="Diet", y="Melarea", fill="Sex") +
labs(y="Area of melanin", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on area of wing melanin") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova", label="p.format")
print(melarea.plot)

blkdens.plot <- ggboxplot(dietcolor1,x="Diet", y="Blkdens", fill="Sex") +
labs(y="Density of melanin pigment", x = "Host Plant Species") + 
ggtitle("Effects of host plant species on black pigment density") +
theme_minimal() +
scale_x_discrete(labels=c("N"="Native", "T"="Tropical")) +
stat_compare_means(method="anova", label="p.format") +
facet_wrap(~Infection)
print(blkdens.plot)

```
```{r MANCOVAs}
#Subset data by sex
femaledata <- as.data.frame(totaldata1 %>% filter(sex=="F")) #22 total females
maledata <- as.data.frame(totaldata1 %>% filter(sex=="M")) #23 total males

#female color
y_f <- cbind(femaledata$Redhue, femaledata$Redsat, femaledata$Redint, femaledata$Melarea, femaledata$Blkdens)
fit <- manova(y_f ~ diet*infection, data=femaledata)
summary.aov(fit)

#male color
y_m <-cbind(maledata$Redhue, maledata$Redsat, maledata$Redint, maledata$Melarea, maledata$Blkdens)
fitm <- manova(y_m ~ diet*infection, data=maledata)
summary.aov(fitm)

#male FW morph
y_mfw <- cbind(maledata$fore.area, maledata$fore.length, maledata$fore.width, maledata$fore.asp.ratio, maledata$fore.round)
fit_mfw <- manova(y_mfw ~ diet*infection, data=maledata)
summary.aov(fit_mfw)

#female FW morph
y_ffw <- cbind(femaledata$fore.area, femaledata$fore.length, femaledata$fore.width, femaledata$fore.asp.ratio, femaledata$fore.round)
fit_ffw <- manova(y_ffw ~ diet*infection, data=femaledata)
summary.aov(fit_ffw)

#male HW morph
y_mhw <- cbind(maledata$hind.area, maledata$hind.length, maledata$hind.width)
fit_mhw <- manova(y_mhw ~ diet*infection, data=maledata)
summary.aov(fit_mhw)

#female HW morph
y_fhw <- cbind(femaledata$hind.area, femaledata$hind.length, femaledata$hind.width)
fit_fhw <- manova(y_fhw ~ diet*infection, data=femaledata)
summary.aov(fit_fhw)

#male asymmetry
y_ma <- cbind(maledata$fore.area.asym, maledata$hind.area.asym, maledata$fore.length.asym, maledata$hind.length.asym)
fit_ma <- manova(y_ma ~ diet*infection, data=maledata)
summary.aov(fit_ma)

#female asymmetry
y_fa <- cbind(femaledata$fore.area.asym, femaledata$hind.area.asym, femaledata$fore.length.asym, femaledata$hind.length.asym)
fit_fa <- manova(y_fa ~ diet*infection, data=femaledata)
summary.aov(fit_fa)



```
```{r calculating effects sizes of diet}
#forewing area
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(fore.area, na.rm=TRUE), sd=sd(fore.area, na.rm=TRUE))

#forewing length
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(fore.length, na.rm=TRUE), sd=sd(fore.length, na.rm=TRUE))

#forewing width
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(fore.width, na.rm=TRUE), sd=sd(fore.width, na.rm=TRUE))

#forewing roundness
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(fore.round, na.rm=TRUE), sd=sd(fore.round, na.rm=TRUE))

#forewing aspect ratio
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(fore.asp.ratio, na.rm=TRUE), sd=sd(fore.asp.ratio, na.rm=TRUE))

#hindwing area
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(hind.area, na.rm=TRUE), sd=sd(hind.area, na.rm=TRUE))

#hindwing length
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(hind.length, na.rm=TRUE), sd=sd(hind.length, na.rm=TRUE))

#hindwing width
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(hind.width, na.rm=TRUE), sd=sd(hind.width, na.rm=TRUE))

#forewing area asym
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(fore.area.asym, na.rm=TRUE), sd=sd(fore.area.asym, na.rm=TRUE))

#forewing  length asym
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(fore.length.asym, na.rm=TRUE), sd=sd(fore.length.asym, na.rm=TRUE))

#hindwing area asym
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(hind.area.asym, na.rm=TRUE), sd=sd(hind.area.asym, na.rm=TRUE))

#hindwing length asym
group_by(dietmorph2, diet, sex) %>%
  summarise(count=n(), mean=mean(hind.length.asym, na.rm=TRUE), sd=sd(hind.length.asym, na.rm=TRUE))


#####################################################

#Red Hue
group_by(maledata, diet) %>%
  summarise(count=n(), mean=mean(Redhue, na.rm=TRUE), sd=sd(Redhue, na.rm=TRUE))

group_by(femaledata, diet) %>%
  summarise(count=n(), mean=mean(Redhue, na.rm=TRUE), sd=sd(Redhue, na.rm=TRUE))

#Red Sat
group_by(maledata, diet) %>%
  summarise(count=n(), mean=mean(Redsat, na.rm=TRUE), sd=sd(Redsat, na.rm=TRUE))

group_by(femaledata, diet) %>%
  summarise(count=n(), mean=mean(Redsat, na.rm=TRUE), sd=sd(Redsat, na.rm=TRUE))

#Red Int
group_by(maledata, diet) %>%
  summarise(count=n(), mean=mean(Redint, na.rm=TRUE), sd=sd(Redint, na.rm=TRUE))

group_by(femaledata, diet) %>%
  summarise(count=n(), mean=mean(Redint, na.rm=TRUE), sd=sd(Redint, na.rm=TRUE))

#Mel Area
group_by(maledata, diet) %>%
  summarise(count=n(), mean=mean(Melarea, na.rm=TRUE), sd=sd(Melarea, na.rm=TRUE))

group_by(femaledata, diet) %>%
  summarise(count=n(), mean=mean(Melarea, na.rm=TRUE), sd=sd(Melarea, na.rm=TRUE))

#Black Density
group_by(maledata, diet) %>%
  summarise(count=n(), mean=mean(Blkdens, na.rm=TRUE), sd=sd(Blkdens, na.rm=TRUE))

group_by(femaledata, diet) %>%
  summarise(count=n(), mean=mean(Blkdens, na.rm=TRUE), sd=sd(Blkdens, na.rm=TRUE))
```

```{r partial effects plot}

#manually creating partial effects plot
lm1 <- lm(fore.area ~ diet + infection + numDaysHatchToEclose, data=totaldata1, na.action=na.exclude)
lm2 <- lm(fore.area ~ numDaysHatchToEclose + infection, data=totaldata1)
lm3 <- lm(numDaysHatchToEclose ~ diet + infection, data=totaldata1)

x <- resid(lm3)
y <- resid(lm2)


plot(x,y,type="n", xlab="Number of Days from Hatch to Eclosure",  ylab="Forewing Area")
part <- lm(y~x)
wx = par("usr")[1:2]
new.x = seq(wx[1],wx[2],len=100)
pred = predict(part, new=data.frame(x=new.x), interval="conf")
lines(new.x,pred[,"fit"],lwd=2)
lines(new.x,pred[,"lwr"],lty=3)
lines(new.x,pred[,"upr"],lty=3)
points(x,y,pch=16,col="steelblue")


#using peplot function from pear package
peplot <- function(lm1,diet,ci=.95, plot_points = "n",
                   xlab=var,ylab=names(mod[12]$lm1)[1],
                   main="Partial Effect Plot",
                   pe_lty=1,pe_lwd=3,pe_col="black",
                   ci_lty=1,ci_lwd=1,ci_col="black",
                   pch_col="black",pch_ty=19,
                   ylim=c(min(pred[,"lwr"]),max(pred[,"upr"]))){
  modDat <- mod[12]$lm1
  modDat1 <- modDat[,-1]
  modDat2 <- modDat[,which(names(modDat)!="diet")]
  x <- resid(lm(modDat1[,var] ~., data=modDat1[,which(names(modDat1)!=var)]))
  y <- resid(lm(modDat2[,1] ~ ., modDat2[,-1]))
  plot(x,y,type=plot_points,xlab=xlab,ylab=ylab,
       ylim=ylim,col=pch_col,pch=pch_ty,
       main=main)
  part <- lm(y~x)
  wx <- par("usr")[1:2]
  new.x <- seq(wx[1],wx[2],len=100)
  pred <- predict(part, new=data.frame(x=new.x), interval="conf",
                  level = ci)
  lines(new.x,pred[,"fit"],lwd=pe_lwd,lty=pe_lty,col=pe_col)
  lines(new.x,pred[,"lwr"],lwd=ci_lwd,lty=ci_lty,col=ci_col)
  lines(new.x,pred[,"upr"],lwd=ci_lwd,lty=ci_lty,col=ci_col)
}

peplot(lm1, var="diet")


```

